//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int MaBaiViet { get; set; }
        public int MaDanhMuc { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public int SoLanXem { get; set; }
        public string Meta_TieuDe { get; set; }
        public string Meta_TuKhoa { get; set; }
        public string Meta_MoTa { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public bool TrangThai { get; set; }
        public string Url { get; set; }
    
        public virtual DanhMucBaiViet DanhMucBaiViet { get; set; }
    }
}
