//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechOffice.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec_VanBan
    {
        public int Id { get; set; }
        public int HoSoCongViecId { get; set; }
        public string SoVanBan { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string NoiDung { get; set; }
        public string TenCoQuan { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual HoSoCongViec HoSoCongViec { get; set; }
    }
}
