//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapTinYKienCoQuan
    {
        public int Id { get; set; }
        public int YKiencoQuanTacNghiepId { get; set; }
        public int UserUploadId { get; set; }
        public string Url { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual TacNghiep_YKienCoQuan TacNghiep_YKienCoQuan { get; set; }
    }
}
