//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuTuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuTuc()
        {
            this.TapTinThuTucs = new HashSet<TapTinThuTuc>();
        }
    
        public int Id { get; set; }
        public string MaThuTuc { get; set; }
        public Nullable<System.DateTime> NgayBanHanh { get; set; }
        public string TenThuTuc { get; set; }
        public int CoQuanThucHienId { get; set; }
        public int LoaiThuTucId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual CoQuan CoQuan { get; set; }
        public virtual LinhVucThuTuc LinhVucThuTuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TapTinThuTuc> TapTinThuTucs { get; set; }
    }
}
