//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnThinhPhat.Resources.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string CongViec_Add_Cancel {
            get {
                return ResourceManager.GetString("CongViec_Add_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string CongViec_Add_QuaTrinhXuLy_Save {
            get {
                return ResourceManager.GetString("CongViec_Add_QuaTrinhXuLy_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string CongViec_Add_Save {
            get {
                return ResourceManager.GetString("CongViec_Add_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string CongViec_Add_VanBanLienQuan_Save {
            get {
                return ResourceManager.GetString("CongViec_Add_VanBanLienQuan_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string CongViec_Detail_Cancel {
            get {
                return ResourceManager.GetString("CongViec_Detail_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string CongViec_Detail_QuaTrinhXuLy_Cancel {
            get {
                return ResourceManager.GetString("CongViec_Detail_QuaTrinhXuLy_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string CongViec_Detail_QuaTrinhXuLy_Delete {
            get {
                return ResourceManager.GetString("CongViec_Detail_QuaTrinhXuLy_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string CongViec_Detail_QuaTrinhXuLy_Edit {
            get {
                return ResourceManager.GetString("CongViec_Detail_QuaTrinhXuLy_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string CongViec_Detail_QuaTrinhXuLy_Save {
            get {
                return ResourceManager.GetString("CongViec_Detail_QuaTrinhXuLy_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string CongViec_Detail_Update {
            get {
                return ResourceManager.GetString("CongViec_Detail_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string CongViec_Detail_VanBanLienQuan_Cancel {
            get {
                return ResourceManager.GetString("CongViec_Detail_VanBanLienQuan_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string CongViec_Detail_VanBanLienQuan_Delete {
            get {
                return ResourceManager.GetString("CongViec_Detail_VanBanLienQuan_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string CongViec_Detail_VanBanLienQuan_Edit {
            get {
                return ResourceManager.GetString("CongViec_Detail_VanBanLienQuan_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string CongViec_Detail_VanBanLienQuan_Save {
            get {
                return ResourceManager.GetString("CongViec_Detail_VanBanLienQuan_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string CongViec_Index_ThemMoi {
            get {
                return ResourceManager.GetString("CongViec_Index_ThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        public static string CongViec_Index_ThongKe {
            get {
                return ResourceManager.GetString("CongViec_Index_ThongKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string CongViec_Index_TimKiem {
            get {
                return ResourceManager.GetString("CongViec_Index_TimKiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê.
        /// </summary>
        public static string CongViec_Statistic_ThongKe {
            get {
                return ResourceManager.GetString("CongViec_Statistic_ThongKe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê công việc.
        /// </summary>
        public static string CongViec_Statistic_ThongKeCongViec {
            get {
                return ResourceManager.GetString("CongViec_Statistic_ThongKeCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        public static string CongViec_Statistic_Tim {
            get {
                return ResourceManager.GetString("CongViec_Statistic_Tim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadFiles_Upload {
            get {
                return ResourceManager.GetString("UploadFiles_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string User_ChangePassword_Save {
            get {
                return ResourceManager.GetString("User_ChangePassword_Save", resourceCulture);
            }
        }
    }
}
