//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnThinhPhat.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực.
        /// </summary>
        public static string CongViec_Add_LinhVuc {
            get {
                return ResourceManager.GetString("CongViec_Add_LinhVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string CongViec_Add_NgayHetHan {
            get {
                return ResourceManager.GetString("CongViec_Add_NgayHetHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hoàn thành.
        /// </summary>
        public static string CongViec_Add_NgayHoanThanh {
            get {
                return ResourceManager.GetString("CongViec_Add_NgayHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày khởi tạo.
        /// </summary>
        public static string CongViec_Add_NgayKhoiTao {
            get {
                return ResourceManager.GetString("CongViec_Add_NgayKhoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string CongViec_Add_NoiDung {
            get {
                return ResourceManager.GetString("CongViec_Add_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung ý kiến trao đổi.
        /// </summary>
        public static string CongViec_Add_NoiDungTraoDoi {
            get {
                return ResourceManager.GetString("CongViec_Add_NoiDungTraoDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phối hợp.
        /// </summary>
        public static string CongViec_Add_PhoiHop {
            get {
                return ResourceManager.GetString("CongViec_Add_PhoiHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ trách.
        /// </summary>
        public static string CongViec_Add_PhuTrach {
            get {
                return ResourceManager.GetString("CongViec_Add_PhuTrach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá trình xử lý.
        /// </summary>
        public static string CongViec_Add_QuaTrinhXuLy {
            get {
                return ResourceManager.GetString("CongViec_Add_QuaTrinhXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ.
        /// </summary>
        public static string CongViec_Add_QuaTrinhXuLy_Gio {
            get {
                return ResourceManager.GetString("CongViec_Add_QuaTrinhXuLy_Gio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string CongViec_Add_QuaTrinhXuLy_Ngay {
            get {
                return ResourceManager.GetString("CongViec_Add_QuaTrinhXuLy_Ngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người thêm.
        /// </summary>
        public static string CongViec_Add_QuaTrinhXuLy_NguoiThem {
            get {
                return ResourceManager.GetString("CongViec_Add_QuaTrinhXuLy_NguoiThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string CongViec_Add_QuaTrinhXuLy_NoiDung {
            get {
                return ResourceManager.GetString("CongViec_Add_QuaTrinhXuLy_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới công việc.
        /// </summary>
        public static string CongViec_Add_Title {
            get {
                return ResourceManager.GetString("CongViec_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string CongViec_Add_TrangThai {
            get {
                return ResourceManager.GetString("CongViec_Add_TrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản liên quan.
        /// </summary>
        public static string CongViec_Add_VanBanLienQuan {
            get {
                return ResourceManager.GetString("CongViec_Add_VanBanLienQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ quan.
        /// </summary>
        public static string CongViec_Add_VanBanLienQuan_CoQuan {
            get {
                return ResourceManager.GetString("CongViec_Add_VanBanLienQuan_CoQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string CongViec_Add_VanBanLienQuan_Ngay {
            get {
                return ResourceManager.GetString("CongViec_Add_VanBanLienQuan_Ngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string CongViec_Add_VanBanLienQuan_NoiDung {
            get {
                return ResourceManager.GetString("CongViec_Add_VanBanLienQuan_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số VB.
        /// </summary>
        public static string CongViec_Add_VanBanLienQuan_SoVanBan {
            get {
                return ResourceManager.GetString("CongViec_Add_VanBanLienQuan_SoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý chính.
        /// </summary>
        public static string CongViec_Add_XuLyChinh {
            get {
                return ResourceManager.GetString("CongViec_Add_XuLyChinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá công việc.
        /// </summary>
        public static string CongViec_Edit_DanhGiaCongViec {
            get {
                return ResourceManager.GetString("CongViec_Edit_DanhGiaCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhân viên.
        /// </summary>
        public static string CongViec_Index_ChonNhanVien {
            get {
                return ResourceManager.GetString("CongViec_Index_ChonNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực công việc.
        /// </summary>
        public static string CongViec_Index_LinhVucCongViec {
            get {
                return ResourceManager.GetString("CongViec_Index_LinhVucCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung công việc.
        /// </summary>
        public static string CongViec_Index_NoiDungCongViec {
            get {
                return ResourceManager.GetString("CongViec_Index_NoiDungCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string CongViec_Index_TatCa {
            get {
                return ResourceManager.GetString("CongViec_Index_TatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string CongViec_Index_TinhTrang {
            get {
                return ResourceManager.GetString("CongViec_Index_TinhTrang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý công việc.
        /// </summary>
        public static string CongViec_Index_Title {
            get {
                return ResourceManager.GetString("CongViec_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò xử lý.
        /// </summary>
        public static string CongViec_Index_VaiTroXuLy {
            get {
                return ResourceManager.GetString("CongViec_Index_VaiTroXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các file đính kèm.
        /// </summary>
        public static string CongViec_List_CacFileDinhKem {
            get {
                return ResourceManager.GetString("CongViec_List_CacFileDinhKem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực.
        /// </summary>
        public static string CongViec_List_LinhVuc {
            get {
                return ResourceManager.GetString("CongViec_List_LinhVuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string CongViec_List_NgayHetHan {
            get {
                return ResourceManager.GetString("CongViec_List_NgayHetHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string CongViec_List_NgayTao {
            get {
                return ResourceManager.GetString("CongViec_List_NgayTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung công việc.
        /// </summary>
        public static string CongViec_List_NoiDungCongViec {
            get {
                return ResourceManager.GetString("CongViec_List_NoiDungCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phối hợp.
        /// </summary>
        public static string CongViec_List_PhoiHop {
            get {
                return ResourceManager.GetString("CongViec_List_PhoiHop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ trách.
        /// </summary>
        public static string CongViec_List_PhuTrach {
            get {
                return ResourceManager.GetString("CongViec_List_PhuTrach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá trình xử lý.
        /// </summary>
        public static string CongViec_List_QuaTrinhXuLy {
            get {
                return ResourceManager.GetString("CongViec_List_QuaTrinhXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string CongViec_List_STT {
            get {
                return ResourceManager.GetString("CongViec_List_STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách công việc.
        /// </summary>
        public static string CongViec_List_Title {
            get {
                return ResourceManager.GetString("CongViec_List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string CongViec_List_TrangThai {
            get {
                return ResourceManager.GetString("CongViec_List_TrangThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xử lý chính.
        /// </summary>
        public static string CongViec_List_XuLyChinh {
            get {
                return ResourceManager.GetString("CongViec_List_XuLyChinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string CongViec_Statistic_ChonNhanVien {
            get {
                return ResourceManager.GetString("CongViec_Statistic_ChonNhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ quan.
        /// </summary>
        public static string CongViec_Statistic_CoQuan {
            get {
                return ResourceManager.GetString("CongViec_Statistic_CoQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string CongViec_Statistic_From {
            get {
                return ResourceManager.GetString("CongViec_Statistic_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực.
        /// </summary>
        public static string CongViec_Statistic_LinhVucCongViec {
            get {
                return ResourceManager.GetString("CongViec_Statistic_LinhVucCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung công việc.
        /// </summary>
        public static string CongViec_Statistic_NoiDungCongViec {
            get {
                return ResourceManager.GetString("CongViec_Statistic_NoiDungCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string CongViec_Statistic_NoiDungVanBan {
            get {
                return ResourceManager.GetString("CongViec_Statistic_NoiDungVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thứ tự hiển thị các công việc.
        /// </summary>
        public static string CongViec_Statistic_OrderShow {
            get {
                return ResourceManager.GetString("CongViec_Statistic_OrderShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số văn bản.
        /// </summary>
        public static string CongViec_Statistic_SoVanBan {
            get {
                return ResourceManager.GetString("CongViec_Statistic_SoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê, tìm kiếm công việc.
        /// </summary>
        public static string CongViec_Statistic_Title {
            get {
                return ResourceManager.GetString("CongViec_Statistic_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string CongViec_Statistic_To {
            get {
                return ResourceManager.GetString("CongViec_Statistic_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái xử lý.
        /// </summary>
        public static string CongViec_Statistic_TrangThaiXuLy {
            get {
                return ResourceManager.GetString("CongViec_Statistic_TrangThaiXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò xử lý.
        /// </summary>
        public static string CongViec_Statistic_VaiTroXuLy {
            get {
                return ResourceManager.GetString("CongViec_Statistic_VaiTroXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng nội vụ huyện Phú Riềng.
        /// </summary>
        public static string Page_Title {
            get {
                return ResourceManager.GetString("Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string TacNghiep_Add_NgayTao {
            get {
                return ResourceManager.GetString("TacNghiep_Add_NgayTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hoàn thành.
        /// </summary>
        public static string TacNghiep_TinhHinhThucHien_DaHoanThanh {
            get {
                return ResourceManager.GetString("TacNghiep_TinhHinhThucHien_DaHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức độ hoàn thành.
        /// </summary>
        public static string TacNghiep_TinhHinhThucHien_MucDoHoanThanh {
            get {
                return ResourceManager.GetString("TacNghiep_TinhHinhThucHien_MucDoHoanThanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cơ quan.
        /// </summary>
        public static string TacNghiep_TinhHinhThucHien_TenCoQuan {
            get {
                return ResourceManager.GetString("TacNghiep_TinhHinhThucHien_TenCoQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các tập tin đính kèm.
        /// </summary>
        public static string UploadFiles_Title {
            get {
                return ResourceManager.GetString("UploadFiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vai trò.
        /// </summary>
        public static string Users_AddUserViewModel_Role {
            get {
                return ResourceManager.GetString("Users_AddUserViewModel_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Users_LoginViewModel_Password {
            get {
                return ResourceManager.GetString("Users_LoginViewModel_Password", resourceCulture);
            }
        }
    }
}
