//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnThinhPhat.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng không hợp lệ.
        /// </summary>
        public static string Account_Login_Incorrect {
            get {
                return ResourceManager.GetString("Account_Login_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn hiện tại đang bị khóa. Xin vui lòng liên hệ với quản trị hệ thống.
        /// </summary>
        public static string Account_Login_Locked {
            get {
                return ResourceManager.GetString("Account_Login_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập tên.
        /// </summary>
        public static string BaseDataViewModel_Name {
            get {
                return ResourceManager.GetString("BaseDataViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối đa là 255 ký tự.
        /// </summary>
        public static string BaseDataViewModel_Name_MaxLength {
            get {
                return ResourceManager.GetString("BaseDataViewModel_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn lĩnh vực công việc.
        /// </summary>
        public static string CongViec_Add_LinhVucCongViec {
            get {
                return ResourceManager.GetString("CongViec_Add_LinhVucCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nội dung công việc.
        /// </summary>
        public static string CongViec_Add_NoiDungCongViec {
            get {
                return ResourceManager.GetString("CongViec_Add_NoiDungCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn người phụ trách.
        /// </summary>
        public static string CongViec_Add_UserPhuTrach {
            get {
                return ResourceManager.GetString("CongViec_Add_UserPhuTrach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn người xử lý chính.
        /// </summary>
        public static string CongViec_Add_UserXuLy {
            get {
                return ResourceManager.GetString("CongViec_Add_UserXuLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập ngày.
        /// </summary>
        public static string CongViec_Statistic_From {
            get {
                return ResourceManager.GetString("CongViec_Statistic_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập ngày.
        /// </summary>
        public static string CongViec_Statistic_To {
            get {
                return ResourceManager.GetString("CongViec_Statistic_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn nhóm cơ quan.
        /// </summary>
        public static string CoQuan_CoQuanViewModel_CoQuanId {
            get {
                return ResourceManager.GetString("CoQuan_CoQuanViewModel_CoQuanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập email.
        /// </summary>
        public static string Home_Contact_Email {
            get {
                return ResourceManager.GetString("Home_Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập họ tên.
        /// </summary>
        public static string Home_Contact_FullName {
            get {
                return ResourceManager.GetString("Home_Contact_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập mã xác nhận.
        /// </summary>
        public static string Home_Contact_MaXacNhan {
            get {
                return ResourceManager.GetString("Home_Contact_MaXacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nội dung.
        /// </summary>
        public static string Home_Contact_NoiDung {
            get {
                return ResourceManager.GetString("Home_Contact_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập tiêu đề.
        /// </summary>
        public static string Home_Contact_Title {
            get {
                return ResourceManager.GetString("Home_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nôi dung phản hồi.
        /// </summary>
        public static string TacNghiep_EditNoiDungYKienCuaCoQuan_NoiDung {
            get {
                return ResourceManager.GetString("TacNghiep_EditNoiDungYKienCuaCoQuan_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn lĩnh vực tác nghiệp.
        /// </summary>
        public static string TacNgiep_AddTacNghiepViewModel_LinhVucTacNghiep {
            get {
                return ResourceManager.GetString("TacNgiep_AddTacNghiepViewModel_LinhVucTacNghiep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập ngày hết hạn.
        /// </summary>
        public static string TacNgiep_AddTacNghiepViewModel_NgayHetHan {
            get {
                return ResourceManager.GetString("TacNgiep_AddTacNghiepViewModel_NgayHetHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập ngày tạo.
        /// </summary>
        public static string TacNgiep_AddTacNghiepViewModel_NgayTao {
            get {
                return ResourceManager.GetString("TacNgiep_AddTacNghiepViewModel_NgayTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nội dung.
        /// </summary>
        public static string TacNgiep_AddTacNghiepViewModel_NoiDung {
            get {
                return ResourceManager.GetString("TacNgiep_AddTacNghiepViewModel_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn cơ quan thực hiện.
        /// </summary>
        public static string ThuTuc_AddThuTuc_CoQuanThucHien {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_CoQuanThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn lĩnh vực thủ tục.
        /// </summary>
        public static string ThuTuc_AddThuTuc_LinhVucThuTuc {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_LinhVucThuTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập ngày ban hành.
        /// </summary>
        public static string ThuTuc_AddThuTuc_NgayBanHanh {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_NgayBanHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nội dung thủ tục.
        /// </summary>
        public static string ThuTuc_AddThuTuc_NoiDung {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_NoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối đa mã thủ tục là 1024 ký tự.
        /// </summary>
        public static string ThuTuc_AddThuTuc_NoiDung_MaxLength {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_NoiDung_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập tên thủ tục.
        /// </summary>
        public static string ThuTuc_AddThuTuc_TenThuTuc {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_TenThuTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối đa mã thủ tục là 1024 ký tự.
        /// </summary>
        public static string ThuTuc_AddThuTuc_TenThuTuc_MaxLength {
            get {
                return ResourceManager.GetString("ThuTuc_AddThuTuc_TenThuTuc_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập mật khẩu.
        /// </summary>
        public static string Users_LoginViewModel_Password {
            get {
                return ResourceManager.GetString("Users_LoginViewModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối thiểu của mật khẩu là 20 ký tự.
        /// </summary>
        public static string Users_LoginViewModel_Password_MaxLength {
            get {
                return ResourceManager.GetString("Users_LoginViewModel_Password_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối thiểu của mật khẩu là 6 ký tự.
        /// </summary>
        public static string Users_LoginViewModel_Password_MinLength {
            get {
                return ResourceManager.GetString("Users_LoginViewModel_Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập tên đăng nhập.
        /// </summary>
        public static string Users_LoginViewModel_UserName {
            get {
                return ResourceManager.GetString("Users_LoginViewModel_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn cơ quan ban hành văn bản.
        /// </summary>
        public static string VanBan_AddVanBan_CoQuanBanHanhVanBan {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_CoQuanBanHanhVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn lĩnh vực văn bản.
        /// </summary>
        public static string VanBan_AddVanBan_LinhVucVanBan {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_LinhVucVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn loại văn bản.
        /// </summary>
        public static string VanBan_AddVanBan_LoaiVanBan {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_LoaiVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập ngày ban hành.
        /// </summary>
        public static string VanBan_AddVanBan_NgayBanHanh {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_NgayBanHanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nội dung văn bản.
        /// </summary>
        public static string VanBan_AddVanBan_NoiDungVanBan {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_NoiDungVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập số văn bản.
        /// </summary>
        public static string VanBan_AddVanBan_SoVanBan {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_SoVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập trích yếu văn bản.
        /// </summary>
        public static string VanBan_AddVanBan_TrichYeuVanBan {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_TrichYeuVanBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiều dài tối đa của trích yếu là 1024 ký tự.
        /// </summary>
        public static string VanBan_AddVanBan_TrichYeuVanBan_MaxLength {
            get {
                return ResourceManager.GetString("VanBan_AddVanBan_TrichYeuVanBan_MaxLength", resourceCulture);
            }
        }
    }
}
