//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnThinhPhat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnThinhPhat.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng không hợ lệ.
        /// </summary>
        public static string Account_Login_Incorrect {
            get {
                return ResourceManager.GetString("Account_Login_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn hiện tại đang bị khóa. Xin vui lòng liên hệ với quản trị hệ thống.
        /// </summary>
        public static string Account_Login_Locked {
            get {
                return ResourceManager.GetString("Account_Login_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn lĩnh vực công việc.
        /// </summary>
        public static string CongViec_Add_LinhVucCongViec {
            get {
                return ResourceManager.GetString("CongViec_Add_LinhVucCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng nhập nội dung công việc.
        /// </summary>
        public static string CongViec_Add_NoiDungCongViec {
            get {
                return ResourceManager.GetString("CongViec_Add_NoiDungCongViec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn người phụ trách.
        /// </summary>
        public static string CongViec_Add_UserPhuTrach {
            get {
                return ResourceManager.GetString("CongViec_Add_UserPhuTrach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin vui lòng chọn người xử lý chính.
        /// </summary>
        public static string CongViec_Add_UserXuLy {
            get {
                return ResourceManager.GetString("CongViec_Add_UserXuLy", resourceCulture);
            }
        }
    }
}
